/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Paneles_Client;

/**
 *
 * @author Acer
 */
public class Panel_Tienda_Client extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Tienda_Client
     */
    public Panel_Tienda_Client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCatágolo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 252, 245));

        lblCatágolo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblCatágolo.setForeground(new java.awt.Color(102, 80, 65));
        lblCatágolo.setText("Catálogo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblCatágolo)
                .addContainerGap(709, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblCatágolo)
                .addContainerGap(821, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lblCatágolo;
    // End of variables declaration//GEN-END:variables
}
